# 텐서(TENSOR)
- 텐서는 배열이나 행렬과 매우 유사한 특수한 자료구조
- 파이토치에서는 텐서를 사용하여 모델의 입력과 출력, 그리고 모델의 매개변수들을 부호화
- 텐서는 GPU나 다른 하드웨어 가속기 실행할 수 있다는 점 제외하면 넘파이의 ndarray와 유사
- 텐서와 넘파이 배열은 종종 동일한 내부 메모릴르 공유할 수 있어 데이터를 복사할 필요 없다
- 텐서는 자동미분에 최적하되어 있다.

In [2]:
import torch
import numpy as np


## 텐서 초기화
텐서는 여러가지 방법으로 초기화할 수 있다.

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [4]:
# 넘파이 배열로 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [6]:
# 다른 텐서로부터 생성하기
# 재정의하지 않으면, 인자로 주어진 텐서의 속성(모양, 자료형) 유지

x_ones = torch.ones_like(x_data) # x_data의 속성을 유지
print(f'Ones Tensor : \n {x_ones} \n')

x_rand = torch.rand_like(x_data, dtype = torch.float) # x_data의 속성을 덮어씀
print(f'Ones Tensor : \n {x_rand} \n')


Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Ones Tensor : 
 tensor([[0.1425, 0.4870],
        [0.1187, 0.3508]]) 



In [7]:
# random or 상수(constant) 값을 사용하기
## shape은 텐서의 차원을 나타내는 튜플로 아래 함수들에서는 출력 텐서의 차원을 결정

shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor : \n {rand_tensor} \n')
print(f'Random Tensor : \n {ones_tensor} \n')
print(f'Random Tensor : \n {zeros_tensor}')

Random Tensor : 
 tensor([[0.4369, 0.3658, 0.8564],
        [0.0800, 0.2873, 0.2833]]) 

Random Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Random Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 텐서의 속성
텐서의 속성은 텐서의 모양, 자료형 및 어느 장치에 저장되는지를 나타낸다.

In [8]:
tensor = torch.rand(3,4)

print(f'Shape of Tensor : \n {tensor.shape} \n')
print(f'Datatype of tensor : \n {tensor.dtype} \n')
print(f'Device tensor is stored on : \n {tensor.device}')

Shape of Tensor : 
 torch.Size([3, 4]) 

Datatype of tensor : 
 torch.float32 

Device tensor is stored on : 
 cpu


# 텐서 연산(Operation)
- 전치, 인덱싱, 슬라이싱, 수학계산, 선형대수, 임의 샘플링 등
- 각 여산들은 GPU에서 실행 가능
- 기본적으로 텐서는 CPU에 생성
- .to 메소들르 사용하면 GPU로 텐서를 명시적으로 이동 가능
- 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이 든다는 것을 기억!!


In [9]:
# GPU가 존재하면 텐서를 이동
if torch.cuda.is_available():
    tensor = tnesor.to('cuda')

In [24]:
# numpy식의 표준 인덱싱과 슬라이싱 

tensor = torch.ones(4,4)
print(f'First row: {tensor[0]}')
print(f'First row: {tensor[:,0]}')
print(f'Last row: {tensor[...,-1]}')
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First row: tensor([1., 1., 1., 1.])
Last row: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [35]:
tensor[:,0].dim(), tensor[...,0].dim()

(1, 1)

텐서합치기 torch.cat을 사용하여 주어진 차원에 따라 일려느이 텐서르 연결할 수 있습니다. torch.cat과 미묘하게 다른 또 다른 텐서 결합 연산인 torch.stack도 참고

In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [12]:
# 산술 연산

# 두 텐서 간의 행렬 곱을 계산 , y1,y2,y3은 모두 같은 값을 갖느다
# tensor.T 는 텐서의 전치를 반환

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# 요소별 곱을 계산, z1,z2,z3는 모두 같은 값을 갖는다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out= z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

단일-요소 텐서  
텐서의 모든 값을 하나로 집계하여 요소가 하나인 텐서의 경우, item()을 사요하여 python숫자값으로 변환

In [13]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


바꿔치기 연산  
연산결과를 피연산자에 저장하는 연산을 바꿔치기 연산이라고 부른다.  
_ 접미사를 갖는다. 예를 들어 : x_copy_(y) 나 x.t_()는 x를 변경한다.

In [14]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


** 참고 **  

바꿔치기 연산은 메로미를 일부 절약하지만, 기록이 즉시 삭제되어 도함수 계산에 문제가 발생할 수 있다.   
따라서, 사용을 권장하지 않는다.

# Numpy 변환(Bridge)
CPU 상의 텐서와 넘파이 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경

In [17]:
t = torch.ones(5)
print(f't: {t}')
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


### numpy 배열을 텐서로 변환하기

In [20]:
n = np.ones(5)
t = torch.from_numpy(n)

In [21]:
np.add(n,1, out = n)
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
